import './globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata = {
	title:
		'Bernard Mbatia Mwangi Portfolio Website/CV, Portfolio website for a professional Quantity Surveyor.',
	description: 'Portfolio website for a professional Quantity Surveyor.',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="min-h-screen flex flex-col">
				<Header />
				<main className="flex-grow">{children}</main>
				<Footer />
			</body>
		</html>
	);
}

// import { Inter } from 'next/font/google';
// import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
// 	return (
// 		<html lang="en">
// 			<body className={inter.className}>{children}</body>
// 		</html>
// 	);
// }
